[package]

name = "shipit"
version = "0.0.1"
authors = ["David Flemström <david.flemstrom@gmail.com>"]

[dependencies.zmq]
git = "https://github.com/cactorium/rust-zmq"
branch = "update"

[dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf.git"

[[example]]
name = "simple"
path = "examples/simple/main.rs"
